spring:
  datasource:
    url: jdbc:postgresql://localhost:${DB_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
server:
  port: ${SERVER_PORT}